# Generated by Django 5.1.3 on 2024-11-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='GENDER',
            field=models.IntegerField(choices=[(1, 'Masculino'), (0, 'Femenino')], default=1),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='LUNG_CANCER',
            field=models.BooleanField(default=False),
        ),
    ]
